apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: elk
  name: es #container prefix name, es-0, es-1, ... etc
spec:
  serviceName: es-cluster # group name ,es-0.es-cluster
  replicas: 3
  selector:
    matchLabels:
      app: es # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: es # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.16.3
        resources:
            requests:
              cpu: 100m
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: es-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-0.es-cluster,es-1.es-cluster,es-2.es-cluster"
          - name: cluster.initial_master_nodes
            value: "es-0,es-1,es-2" # DO NOT add es-cluster suffix, It takes me so so much time to resolve it
          - name: discovery.zen.minimum_master_nodes
            value: "2"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
      initContainers:
      - name: fix-permissions
        image: busybox:1.28
        command: 
          - sh
          - "-c"
          - |
            chown -R 1000:1000 /usr/share/elasticsearch/data
            sysctl -w vm.max_map_count=262144
            ulimit -n 65535
        securityContext:
          privileged: true
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-data
          hostPath:
            path: /opt/data/es-data 