apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.16.3
        resources:
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://es-cluster:9200 # The domain es-cluster will resolve to a list of IP addresses for the 3 Elasticsearch Pods. 
        ports:
        - containerPort: 5601