apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: es-cluster
spec:
  selector:
    app: es #has to match .spec.template.metadata.labels
  ports:
  - name: transport
    port: 9300
    protocol: TCP