apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: kibana
spec:
  selector:
    app: kibana #has to match .spec.template.metadata.labels
  ports:
  - name: http
    port: 5601
    protocol: TCP